import { AudioTrack, Series, Artist, CategoryInfo } from '@/types/audio';

// Canonical Archival Covers per Series & Standalone Audio
export const COVERS = {
  krishnaSmriti: '/covers/krishna-smriti.svg',
  ekOmkarSatnam: '/covers/ek-omkar-satnam.svg',
  mahaveerVani: '/covers/mahaveer-vani.svg',
  mareHeJogiMaro: '/covers/mare-he-jogi-maro.svg',
  nirvanUpanishad: '/covers/nirvan-upanishad.svg',
  naadbrahm: '/covers/naadbrahm.svg',
  mantraDhyan: '/covers/mantra-dhyan.svg',
  antarPravesh: '/covers/antar-pravesh.svg',
  andhkarDhyan: '/covers/andhkar-dhyan.svg',
  oshoPortrait: '/covers/krishna-smriti.svg',
  defaultCover: '/covers/default-cover.svg',
};

export const SEED_CATEGORIES: CategoryInfo[] = [
  {
    id: 'discourses',
    title: 'Discourses & Talks',
    description: 'Spontaneous dialogues on human consciousness, existence, and inner awakening.',
    coverImage: COVERS.krishnaSmriti,
    count: 40,
  },
  {
    id: 'philosophy',
    title: 'Philosophy & Gita',
    description: 'Direct inquiry into non-dual awareness, Mahavira, and timeless spiritual texts.',
    coverImage: COVERS.mahaveerVani,
    count: 20,
  },
  {
    id: 'upanishads',
    title: 'Upanishad Series',
    description: 'Commentaries unlocking the mystical heights of ancient Upanishadic wisdom.',
    coverImage: COVERS.nirvanUpanishad,
    count: 4,
  },
  {
    id: 'meditation',
    title: 'Meditation & Stillness',
    description: 'Guided meditative techniques and sound resonance for deep inward turning.',
    coverImage: COVERS.naadbrahm,
    count: 4,
  },
];

export const SEED_ARTISTS: Artist[] = [
  {
    id: 'osho',
    slug: 'osho',
    name: 'Osho',
    role: 'Philosopher, Mystic & Speaker',
    bio: 'Spontaneous discourses exploring consciousness, the Upanishads, the Gita, meditation, and inner freedom without dogma.',
    image: COVERS.oshoPortrait,
    trackCount: 68,
    seriesCount: 5,
    tags: ['Discourses', 'Upanishads', 'Meditation', 'Gita', 'Philosophy'],
  },
];

export const SEED_SERIES: Series[] = [
  {
    id: 'krishna-smriti',
    slug: 'krishna-smriti',
    title: 'Krishna Smriti',
    subtitle: 'The Timeless Dimensions of Krishna',
    description: 'Spontaneous discourses exploring the multidimensionality of Krishna — dancer, warrior, lover, statesman, and the ultimate celebration of life without guilt or division.',
    artistId: 'osho',
    artistName: 'Osho',
    category: 'Discourses',
    coverImage: COVERS.krishnaSmriti,
    totalTracks: 17,
    totalDuration: 39960,
    trackIds: [
      'krishna-smriti-01', 'krishna-smriti-02', 'krishna-smriti-03', 'krishna-smriti-04', 'krishna-smriti-05',
      'krishna-smriti-09', 'krishna-smriti-11', 'krishna-smriti-12', 'krishna-smriti-13', 'krishna-smriti-14',
      'krishna-smriti-15', 'krishna-smriti-17', 'krishna-smriti-18', 'krishna-smriti-19', 'krishna-smriti-20',
      'krishna-smriti-21', 'krishna-smriti-22'
    ],
    language: 'Hindi',
    tags: ['Krishna', 'Gita', 'Celebration', 'Consciousness', 'Discourses'],
    featured: true,
    published: true,
    createdAt: '2024-01-15T00:00:00Z',
  },
  {
    id: 'ek-omkar-satnam',
    slug: 'ek-omkar-satnam',
    title: 'Ek Omkar Satnam',
    subtitle: 'Discourses on Japji Sahib of Guru Nanak',
    description: 'The sublime ecstasy and devotion of Nanak’s songs of divine remembrance, surrender, and non-dual awakening.',
    artistId: 'osho',
    artistName: 'Osho',
    category: 'Discourses',
    coverImage: COVERS.ekOmkarSatnam,
    totalTracks: 20,
    totalDuration: 72000,
    trackIds: Array.from({ length: 20 }, (_, i) => `ek-omkar-satnam-${(i + 1).toString().padStart(2, '0')}`),
    language: 'Hindi',
    tags: ['Nanak', 'Japji Sahib', 'Devotion', 'Awareness', 'Discourses'],
    featured: true,
    published: true,
    createdAt: '2024-02-01T00:00:00Z',
  },
  {
    id: 'mahaveer-vani',
    slug: 'mahaveer-vani',
    title: 'Mahaveer Vani',
    subtitle: 'The Supreme Wisdom of Mahavira',
    description: 'A deep psychological and spiritual treatise on Ahimsa, Anekantavada, Aparigraha, and fearless conquest of the self.',
    artistId: 'osho',
    artistName: 'Osho',
    category: 'Philosophy',
    coverImage: COVERS.mahaveerVani,
    totalTracks: 20,
    totalDuration: 72000,
    trackIds: Array.from({ length: 20 }, (_, i) => `mahaveer-vani-${(i + 1).toString().padStart(2, '0')}`),
    language: 'Hindi',
    tags: ['Mahaveer', 'Ahimsa', 'Consciousness', 'Philosophy'],
    featured: true,
    published: true,
    createdAt: '2024-02-15T00:00:00Z',
  },
  {
    id: 'mare-he-jogi-maro',
    slug: 'mare-he-jogi-maro',
    title: 'Mare He Jogi Maro',
    subtitle: 'Gorakhnath & The Mystic Path of Rebirth',
    description: 'Commentaries on Gorakhnath and the Siddha lineage of inner transformation through psychological death and rebirth.',
    artistId: 'osho',
    artistName: 'Osho',
    category: 'Discourses',
    coverImage: COVERS.mareHeJogiMaro,
    totalTracks: 3,
    totalDuration: 10800,
    trackIds: ['mare-he-jogi-maro-01', 'mare-he-jogi-maro-02', 'mare-he-jogi-maro-03'],
    language: 'Hindi',
    tags: ['Gorakhnath', 'Mysticism', 'Death & Rebirth', 'Yoga'],
    featured: false,
    published: true,
    createdAt: '2024-03-01T00:00:00Z',
  },
  {
    id: 'nirvan-upanishad',
    slug: 'nirvan-upanishad',
    title: 'Nirvan Upanishad',
    subtitle: 'The Flight Beyond Ego to Boundless Being',
    description: 'The highest flight of Upanishadic wisdom on Nirvana — the flame going out, leaving only boundless, radiant sky.',
    artistId: 'osho',
    artistName: 'Osho',
    category: 'Upanishads',
    coverImage: COVERS.nirvanUpanishad,
    totalTracks: 4,
    totalDuration: 14400,
    trackIds: ['nirvan-upanishad-01', 'nirvan-upanishad-02', 'nirvan-upanishad-03', 'nirvan-upanishad-04'],
    language: 'Hindi',
    tags: ['Upanishad', 'Nirvana', 'Liberation', 'Enlightenment'],
    featured: false,
    published: true,
    createdAt: '2024-03-10T00:00:00Z',
  },
];

// Helper to construct Krishna Smriti tracks
const krishnaParts = [
  { num: 1, p: '01', dur: 1371 },
  { num: 2, p: '02', dur: 2286 },
  { num: 3, p: '03', dur: 1836 },
  { num: 4, p: '04', dur: 2118 },
  { num: 5, p: '05', dur: 1227 },
  { num: 9, p: '09', dur: 1105 },
  { num: 11, p: '11', dur: 1778 },
  { num: 12, p: '12', dur: 1986 },
  { num: 13, p: '13', dur: 1944 },
  { num: 14, p: '14', dur: 2810 },
  { num: 15, p: '15', dur: 2122 },
  { num: 17, p: '17', dur: 1440 },
  { num: 18, p: '18', dur: 2625 },
  { num: 19, p: '19', dur: 1829 },
  { num: 20, p: '20', dur: 2720 },
  { num: 21, p: '21', dur: 1338 },
  { num: 22, p: '22', dur: 1825 },
];

const krishnaTracks: AudioTrack[] = krishnaParts.map(({ num, p, dur }) => ({
  id: `krishna-smriti-${p}`,
  slug: `krishna-smriti-${p}`,
  title: `Krishna Smriti — Part ${p}`,
  subtitle: `Discourse ${p}`,
  description: `Discourse ${p} on the timeless dimensions of Krishna.`,
  artistId: 'osho',
  artistName: 'Osho',
  seriesId: 'krishna-smriti',
  seriesName: 'Krishna Smriti',
  category: 'Discourses',
  language: 'Hindi',
  duration: dur,
  trackNumber: num,
  audioUrl: `osho/krishna-smriti/OSHO-Krishna_Smriti_${p}.mp3`,
  coverImage: COVERS.krishnaSmriti,
  tags: ['krishna', 'gita', 'osho', 'discourses'],
  releaseDate: '1970-10-01',
  isDownloadable: true,
  isExplicit: false,
  published: true,
  playCount: 1200 + num * 50,
  createdAt: '2024-01-15T00:00:00Z',
}));

// Helper for Ek Omkar Satnam tracks (20 parts)
const ekOmkarTracks: AudioTrack[] = Array.from({ length: 20 }, (_, idx) => {
  const num = idx + 1;
  const p = num.toString().padStart(2, '0');
  return {
    id: `ek-omkar-satnam-${p}`,
    slug: `ek-omkar-satnam-${p}`,
    title: `Ek Omkar Satnam — Part ${p}`,
    subtitle: `Japji Sahib Discourse ${p}`,
    description: `Discourse ${p} on Japji Sahib of Guru Nanak.`,
    artistId: 'osho',
    artistName: 'Osho',
    seriesId: 'ek-omkar-satnam',
    seriesName: 'Ek Omkar Satnam',
    category: 'Discourses',
    language: 'Hindi',
    duration: 3600,
    trackNumber: num,
    audioUrl: `osho/OSHO-Ek_Omkar_Satnam/OSHO-Ek_Omkar_Satnam_${p}.mp3`,
    coverImage: COVERS.ekOmkarSatnam,
    tags: ['nanak', 'japji-sahib', 'devotion', 'osho'],
    releaseDate: '1975-01-01',
    isDownloadable: true,
    isExplicit: false,
    published: true,
    playCount: 900 + num * 30,
    createdAt: '2024-02-01T00:00:00Z',
  };
});

// Helper for Mahaveer Vani tracks (20 parts)
const mahaveerTracks: AudioTrack[] = Array.from({ length: 20 }, (_, idx) => {
  const num = idx + 1;
  const p = num.toString().padStart(2, '0');
  return {
    id: `mahaveer-vani-${p}`,
    slug: `mahaveer-vani-${p}`,
    title: `Mahaveer Vani — Part ${p}`,
    subtitle: `Mahavira Discourse ${p}`,
    description: `Discourse ${p} on the supreme message of Mahavira.`,
    artistId: 'osho',
    artistName: 'Osho',
    seriesId: 'mahaveer-vani',
    seriesName: 'Mahaveer Vani',
    category: 'Philosophy',
    language: 'Hindi',
    duration: 3600,
    trackNumber: num,
    audioUrl: `osho/OSHO-Mahaveer_Vani/OSHO-Mahaveer_Vani_${p}.mp3`,
    coverImage: COVERS.mahaveerVani,
    tags: ['mahaveer', 'ahimsa', 'philosophy', 'osho'],
    releaseDate: '1974-05-01',
    isDownloadable: true,
    isExplicit: false,
    published: true,
    playCount: 850 + num * 25,
    createdAt: '2024-02-15T00:00:00Z',
  };
});

// Helper for Mare He Jogi Maro tracks (3 parts)
const mareHeJogiTracks: AudioTrack[] = [1, 2, 3].map((num) => {
  const p = num.toString().padStart(2, '0');
  return {
    id: `mare-he-jogi-maro-${p}`,
    slug: `mare-he-jogi-maro-${p}`,
    title: `Mare He Jogi Maro — Part ${p}`,
    subtitle: `Gorakhnath Discourse ${p}`,
    description: `Discourse ${p} on Gorakhnath and the mystical path of death and rebirth.`,
    artistId: 'osho',
    artistName: 'Osho',
    seriesId: 'mare-he-jogi-maro',
    seriesName: 'Mare He Jogi Maro',
    category: 'Discourses',
    language: 'Hindi',
    duration: 3600,
    trackNumber: num,
    audioUrl: `osho/OSHO-Mare_He_Jogi_Maro/OSHO-Mare_He_Jogi_Maro_${p}.mp3`,
    coverImage: COVERS.mareHeJogiMaro,
    tags: ['gorakhnath', 'mysticism', 'yoga', 'osho'],
    releaseDate: '1978-01-01',
    isDownloadable: true,
    isExplicit: false,
    published: true,
    playCount: 650 + num * 40,
    createdAt: '2024-03-01T00:00:00Z',
  };
});

// Helper for Nirvan Upanishad tracks (4 parts)
const nirvanTracks: AudioTrack[] = [1, 2, 3, 4].map((num) => {
  const p = num.toString().padStart(2, '0');
  return {
    id: `nirvan-upanishad-${p}`,
    slug: `nirvan-upanishad-${p}`,
    title: `Nirvan Upanishad — Part ${p}`,
    subtitle: `Upanishad Discourse ${p}`,
    description: `Discourse ${p} on Nirvan Upanishad — the flame going out to boundless being.`,
    artistId: 'osho',
    artistName: 'Osho',
    seriesId: 'nirvan-upanishad',
    seriesName: 'Nirvan Upanishad',
    category: 'Upanishads',
    language: 'Hindi',
    duration: 3600,
    trackNumber: num,
    audioUrl: `osho/OSHO-Nirvan_Upanishad/OSHO-Nirvan_Upanishad_${p}.mp3`,
    coverImage: COVERS.nirvanUpanishad,
    tags: ['upanishad', 'nirvana', 'liberation', 'osho'],
    releaseDate: '1972-01-01',
    isDownloadable: true,
    isExplicit: false,
    published: true,
    playCount: 720 + num * 35,
    createdAt: '2024-03-10T00:00:00Z',
  };
});

// Standalone Singles from osho/singles/
const standaloneTracks: AudioTrack[] = [
  {
    id: 'naadbrahm-dhyan',
    slug: 'naadbrahm-dhyan',
    title: 'Naadbrahm Meditation',
    subtitle: 'Sound Resonating in Body & Mind',
    description: 'A Tibetan humming technique creating inner resonance, balancing the nervous system, and centering awareness.',
    artistId: 'osho',
    artistName: 'Osho',
    category: 'Meditation',
    language: 'Hindi',
    duration: 3600,
    trackNumber: 1,
    audioUrl: 'osho/singles/Naadbrahm_Osho.mp3',
    coverImage: COVERS.naadbrahm,
    tags: ['meditation', 'humming', 'sound', 'osho'],
    releaseDate: '1975-01-01',
    isDownloadable: true,
    isExplicit: false,
    published: true,
    playCount: 2400,
    createdAt: '2024-01-01T00:00:00Z',
  },
  {
    id: 'mantra-dhyan',
    slug: 'mantra-dhyan',
    title: 'Mantra Dhyan',
    subtitle: 'Sacred Vibrational Awakening',
    description: 'Sound as a vehicle to travel beyond sound: rhythmic chanting dissolving into spontaneous inner stillness.',
    artistId: 'osho',
    artistName: 'Osho',
    category: 'Meditation',
    language: 'Hindi',
    duration: 3600,
    trackNumber: 2,
    audioUrl: 'osho/singles/Mantra_Dhyan.mp3',
    coverImage: COVERS.mantraDhyan,
    tags: ['mantra', 'dhyan', 'meditation', 'osho'],
    releaseDate: '1975-01-01',
    isDownloadable: true,
    isExplicit: false,
    published: true,
    playCount: 1850,
    createdAt: '2024-01-01T00:00:00Z',
  },
  {
    id: 'antar-pravesh',
    slug: 'antar-pravesh',
    title: 'Antar Pravesh',
    subtitle: 'Entering the Inner Sanctum',
    description: 'Direct guided journey turning perception from external objects toward the conscious observer within.',
    artistId: 'osho',
    artistName: 'Osho',
    category: 'Meditation',
    language: 'Hindi',
    duration: 3600,
    trackNumber: 3,
    audioUrl: 'osho/singles/Antar_Pravesh.mp3',
    coverImage: COVERS.antarPravesh,
    tags: ['inward', 'stillness', 'meditation', 'osho'],
    releaseDate: '1975-01-01',
    isDownloadable: true,
    isExplicit: false,
    published: true,
    playCount: 1620,
    createdAt: '2024-01-01T00:00:00Z',
  },
  {
    id: 'andhkar-dhyan',
    slug: 'andhkar-dhyan',
    title: 'Andhkar Dhyan',
    subtitle: 'Meditation in Pure Darkness',
    description: 'Dissolving spatial boundaries through unconditional acceptance of velvety darkness and pure silent presence.',
    artistId: 'osho',
    artistName: 'Osho',
    category: 'Meditation',
    language: 'Hindi',
    duration: 3600,
    trackNumber: 4,
    audioUrl: 'osho/singles/Andhkar_Dhyan.mp3',
    coverImage: COVERS.andhkarDhyan,
    tags: ['darkness', 'witness', 'meditation', 'osho'],
    releaseDate: '1975-01-01',
    isDownloadable: true,
    isExplicit: false,
    published: true,
    playCount: 1410,
    createdAt: '2024-01-01T00:00:00Z',
  },
];

export const SEED_TRACKS: AudioTrack[] = [
  ...krishnaTracks,
  ...ekOmkarTracks,
  ...mahaveerTracks,
  ...mareHeJogiTracks,
  ...nirvanTracks,
  ...standaloneTracks,
];
