import { AudioTrack, Series, Artist, CategoryInfo } from '@/types/audio';

export const SEED_CATEGORIES: CategoryInfo[] = [
  {
    id: 'discourses',
    title: 'Discourses & Talks',
    description: 'Deep dialogues on consciousness, existence, and inner awakening.',
    coverImage: 'https://images.unsplash.com/photo-1507692049790-de58290a4334?q=80&w=800&auto=format&fit=crop',
    count: 14,
  },
  {
    id: 'meditation',
    title: 'Meditation & Stillness',
    description: 'Guided meditations, breathing awareness, and sound-based techniques.',
    coverImage: 'https://images.unsplash.com/photo-1506126613408-eca07ce68773?q=80&w=800&auto=format&fit=crop',
    count: 8,
  },
  {
    id: 'philosophy',
    title: 'Philosophy & Gita',
    description: 'Explorations of timeless texts, Advaita, Zen, and the Bhagavad Gita.',
    coverImage: 'https://images.unsplash.com/photo-1457369804613-52c61a468e7d?q=80&w=800&auto=format&fit=crop',
    count: 10,
  },
  {
    id: 'music',
    title: 'Classical & Ambient',
    description: 'Morning ragas, Indian bamboo flute, sitar, and contemplative soundscapes.',
    coverImage: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?q=80&w=800&auto=format&fit=crop',
    count: 12,
  },
  {
    id: 'audiobooks',
    title: 'Audiobooks & Classics',
    description: 'Full-length narrations of philosophical masterpieces and spiritual classics.',
    coverImage: 'https://images.unsplash.com/photo-1497633762265-9d179a990aa6?q=80&w=800&auto=format&fit=crop',
    count: 6,
  },
  {
    id: 'chants',
    title: 'Chants & Mantras',
    description: 'Ancient Vedic hymns, Sanskrit chanting, and meditative resonance.',
    coverImage: 'https://images.unsplash.com/photo-1519817650390-64a93db51149?q=80&w=800&auto=format&fit=crop',
    count: 7,
  },
];

export const SEED_ARTISTS: Artist[] = [
  {
    id: 'osho',
    slug: 'osho',
    name: 'Osho',
    role: 'Philosopher, Mystic & Speaker',
    bio: 'Spontaneous discourses given to seekers from across the world over three decades, exploring human consciousness, meditation, love, and truth.',
    image: 'https://images.unsplash.com/photo-1544717305-2782549b5136?q=80&w=800&auto=format&fit=crop',
    trackCount: 18,
    seriesCount: 4,
    tags: ['Discourses', 'Gita', 'Zen', 'Meditation'],
  },
  {
    id: 'j-krishnamurti',
    slug: 'j-krishnamurti',
    name: 'J. Krishnamurti',
    role: 'Philosopher & Educator',
    bio: 'Talks on the nature of mind, freedom from the known, fear, time, and unconditional inquiry without authority.',
    image: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?q=80&w=800&auto=format&fit=crop',
    trackCount: 6,
    seriesCount: 1,
    tags: ['Philosophy', 'Inquiry', 'Consciousness'],
  },
  {
    id: 'hariprasad-chaurasia',
    slug: 'hariprasad-chaurasia',
    name: 'Pt. Hariprasad Chaurasia',
    role: 'Bansuri Maestro',
    bio: 'Legendary Indian classical flautist renowned worldwide for evoking serene meditative states through deep raga exploration.',
    image: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?q=80&w=800&auto=format&fit=crop',
    trackCount: 5,
    seriesCount: 1,
    tags: ['Music', 'Classical', 'Flute', 'Raga'],
  },
  {
    id: 'ananda-soundscapes',
    slug: 'ananda-soundscapes',
    name: 'Ananda Soundscapes',
    role: 'Acoustic Meditation Collective',
    bio: 'Ambient acoustic recordings of singing bowls, natural mountain streams, and drone harmonics designed for deep focus and sleep.',
    image: 'https://images.unsplash.com/photo-1518241353330-0f7941c2d9b5?q=80&w=800&auto=format&fit=crop',
    trackCount: 7,
    seriesCount: 2,
    tags: ['Meditation', 'Sound Healing', 'Ambient'],
  },
];

export const SEED_SERIES: Series[] = [
  {
    id: 'krishna-smriti',
    slug: 'krishna-smriti',
    title: 'Krishna Smriti',
    subtitle: 'The Timeless Dimensions of Krishna',
    description: 'A revolutionary series of spontaneous discourses exploring the multidimensionality of Krishna — dancer, warrior, lover, statesman, and the ultimate celebration of life without guilt or division.',
    artistId: 'osho',
    artistName: 'Osho',
    category: 'Discourses',
    coverImage: 'https://images.unsplash.com/photo-1579783902614-a3fb3927b675?q=80&w=800&auto=format&fit=crop',
    totalTracks: 5,
    totalDuration: 23640, // ~6 hours 34 min
    trackIds: [
      'krishna-smriti-01',
      'krishna-smriti-02',
      'krishna-smriti-03',
      'krishna-smriti-04',
      'krishna-smriti-05',
    ],
    language: 'Hindi',
    tags: ['Krishna', 'Gita', 'Celebration', 'Consciousness', 'Discourses'],
    featured: true,
    published: true,
    createdAt: '2024-01-15T00:00:00Z',
  },
  {
    id: 'silent-mind-meditations',
    slug: 'silent-mind-meditations',
    title: 'Silent Mind: Daily Awakening',
    subtitle: 'Breath, Sound, and Witnessing Awareness',
    description: 'A structured progressive series of mindful listening exercises guiding the practitioner from bodily awareness to effortless silent witnessing.',
    artistId: 'ananda-soundscapes',
    artistName: 'Ananda Soundscapes',
    category: 'Meditation',
    coverImage: 'https://images.unsplash.com/photo-1506126613408-eca07ce68773?q=80&w=800&auto=format&fit=crop',
    totalTracks: 3,
    totalDuration: 5400, // 90 min
    trackIds: [
      'silent-mind-01',
      'silent-mind-02',
      'silent-mind-03',
    ],
    language: 'English',
    tags: ['Meditation', 'Mindfulness', 'Breathwork', 'Stillness'],
    featured: true,
    published: true,
    createdAt: '2024-02-01T00:00:00Z',
  },
  {
    id: 'morning-ragas-trilogy',
    slug: 'morning-ragas-trilogy',
    title: 'Morning Ragas of Sunrise',
    subtitle: 'Bhairav, Todi, and Ahir Bhairav',
    description: 'Sublime bansuri improvisations tuned to the quiet transition of dawn, evoking peace, clarity, and deep emotional resonance.',
    artistId: 'hariprasad-chaurasia',
    artistName: 'Pt. Hariprasad Chaurasia',
    category: 'Music',
    coverImage: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?q=80&w=800&auto=format&fit=crop',
    totalTracks: 3,
    totalDuration: 7200, // 120 min
    trackIds: [
      'morning-raga-01',
      'morning-raga-02',
      'morning-raga-03',
    ],
    language: 'Instrumental',
    tags: ['Classical', 'Raga', 'Flute', 'Morning'],
    featured: true,
    published: true,
    createdAt: '2024-02-10T00:00:00Z',
  },
  {
    id: 'the-nature-of-thought',
    slug: 'the-nature-of-thought',
    title: 'The Nature of Thought and Fear',
    subtitle: 'Dialogues on Direct Perception',
    description: 'An unsparing inquiry into psychological conditioning, observation without the observer, and living with profound clarity.',
    artistId: 'j-krishnamurti',
    artistName: 'J. Krishnamurti',
    category: 'Philosophy',
    coverImage: 'https://images.unsplash.com/photo-1457369804613-52c61a468e7d?q=80&w=800&auto=format&fit=crop',
    totalTracks: 2,
    totalDuration: 6600, // 110 min
    trackIds: [
      'krishnamurti-thought-01',
      'krishnamurti-thought-02',
    ],
    language: 'English',
    tags: ['Philosophy', 'Mind', 'Krishnamurti', 'Awareness'],
    featured: false,
    published: true,
    createdAt: '2024-03-01T00:00:00Z',
  },
];

export const SEED_TRACKS: AudioTrack[] = [
  // Krishna Smriti Series
  {
    id: 'krishna-smriti-01',
    slug: 'krishna-smriti-01',
    title: 'Krishna Smriti — Part 01',
    subtitle: 'Krishna: A Total Acceptance of Life',
    description: 'An introductory discourse illuminating why Krishna stands unique in human history as a totality that denies nothing of life.',
    artistId: 'osho',
    artistName: 'Osho',
    seriesId: 'krishna-smriti',
    seriesName: 'Krishna Smriti',
    category: 'Discourses',
    language: 'Hindi',
    duration: 4200, // 1 hr 10 min
    trackNumber: 1,
    audioUrl: 'https://cdn.pixabay.com/download/audio/2022/05/27/audio_1808fbf07a.mp3?filename=relaxing-mountains-nature-walk-112191.mp3',
    coverImage: 'https://images.unsplash.com/photo-1579783902614-a3fb3927b675?q=80&w=800&auto=format&fit=crop',
    tags: ['krishna', 'philosophy', 'osho', 'life', 'acceptance'],
    releaseDate: '1970-10-01',
    isDownloadable: true,
    isExplicit: false,
    published: true,
    playCount: 1420,
    createdAt: '2024-01-15T00:00:00Z',
  },
  {
    id: 'krishna-smriti-02',
    slug: 'krishna-smriti-02',
    title: 'Krishna Smriti — Part 02',
    subtitle: 'The Flute and The Battlefield',
    description: 'Contemplating how flute-playing in Vrindavan and blowing the conch in Kurukshetra are expressions of the same undivided consciousness.',
    artistId: 'osho',
    artistName: 'Osho',
    seriesId: 'krishna-smriti',
    seriesName: 'Krishna Smriti',
    category: 'Discourses',
    language: 'Hindi',
    duration: 6952, // 1 hr 55 min 52 sec
    trackNumber: 2,
    audioUrl: 'https://cdn.pixabay.com/download/audio/2022/03/15/audio_c8c8a73467.mp3?filename=meditation-109038.mp3',
    coverImage: 'https://images.unsplash.com/photo-1579783902614-a3fb3927b675?q=80&w=800&auto=format&fit=crop',
    tags: ['krishna', 'gita', 'kurukshetra', 'osho', 'awareness'],
    releaseDate: '1970-10-02',
    isDownloadable: true,
    isExplicit: false,
    published: true,
    playCount: 1180,
    createdAt: '2024-01-15T00:00:00Z',
  },
  {
    id: 'krishna-smriti-03',
    slug: 'krishna-smriti-03',
    title: 'Krishna Smriti — Part 03',
    subtitle: 'The Dance of Existence (Raas-Leela)',
    description: 'An inquiry into celebrating existence with innocence, joy, and the inner dimension of devotion.',
    artistId: 'osho',
    artistName: 'Osho',
    seriesId: 'krishna-smriti',
    seriesName: 'Krishna Smriti',
    category: 'Discourses',
    language: 'Hindi',
    duration: 4164, // 1 hr 09 min 24 sec
    trackNumber: 3,
    audioUrl: 'https://cdn.pixabay.com/download/audio/2022/01/18/audio_d0a13f69d2.mp3?filename=ambient-piano-amp-strings-10711.mp3',
    coverImage: 'https://images.unsplash.com/photo-1579783902614-a3fb3927b675?q=80&w=800&auto=format&fit=crop',
    tags: ['krishna', 'raas', 'celebration', 'love', 'mysticism'],
    releaseDate: '1970-10-03',
    isDownloadable: true,
    isExplicit: false,
    published: true,
    playCount: 2040,
    createdAt: '2024-01-15T00:00:00Z',
  },
  {
    id: 'krishna-smriti-04',
    slug: 'krishna-smriti-04',
    title: 'Krishna Smriti — Part 04',
    subtitle: 'Action Without Attachment (Nishkama Karma)',
    description: 'How to act completely and passionately without being chained to anxiety over the fruits of action.',
    artistId: 'osho',
    artistName: 'Osho',
    seriesId: 'krishna-smriti',
    seriesName: 'Krishna Smriti',
    category: 'Discourses',
    language: 'Hindi',
    duration: 4320, // 1 hr 12 min
    trackNumber: 4,
    audioUrl: 'https://cdn.pixabay.com/download/audio/2022/11/06/audio_946a815a51.mp3?filename=calm-ambient-126245.mp3',
    coverImage: 'https://images.unsplash.com/photo-1579783902614-a3fb3927b675?q=80&w=800&auto=format&fit=crop',
    tags: ['karma-yoga', 'gita', 'action', 'detachment'],
    releaseDate: '1970-10-04',
    isDownloadable: true,
    isExplicit: false,
    published: true,
    playCount: 950,
    createdAt: '2024-01-15T00:00:00Z',
  },
  {
    id: 'krishna-smriti-05',
    slug: 'krishna-smriti-05',
    title: 'Krishna Smriti — Part 05',
    subtitle: 'The Ultimate Freedom',
    description: 'Concluding dialogue on freedom from fear, dogma, guilt, and discovering the divine play (Leela) in daily life.',
    artistId: 'osho',
    artistName: 'Osho',
    seriesId: 'krishna-smriti',
    seriesName: 'Krishna Smriti',
    category: 'Discourses',
    language: 'Hindi',
    duration: 4004, // 1 hr 06 min 44 sec
    trackNumber: 5,
    audioUrl: 'https://cdn.pixabay.com/download/audio/2022/05/27/audio_1808fbf07a.mp3?filename=relaxing-mountains-nature-walk-112191.mp3',
    coverImage: 'https://images.unsplash.com/photo-1579783902614-a3fb3927b675?q=80&w=800&auto=format&fit=crop',
    tags: ['freedom', 'leela', 'consciousness', 'osho'],
    releaseDate: '1970-10-05',
    isDownloadable: true,
    isExplicit: false,
    published: true,
    playCount: 880,
    createdAt: '2024-01-15T00:00:00Z',
  },

  // Silent Mind Meditations
  {
    id: 'silent-mind-01',
    slug: 'silent-mind-01',
    title: 'Breath as an Anchor',
    subtitle: 'Foundations of Pranic Awareness',
    description: 'A 30-minute immersive audio guide on tracking the subtle natural rhythm of breathing without control or interference.',
    artistId: 'ananda-soundscapes',
    artistName: 'Ananda Soundscapes',
    seriesId: 'silent-mind-meditations',
    seriesName: 'Silent Mind: Daily Awakening',
    category: 'Meditation',
    language: 'English',
    duration: 1800, // 30 min
    trackNumber: 1,
    audioUrl: 'https://cdn.pixabay.com/download/audio/2022/03/15/audio_c8c8a73467.mp3?filename=meditation-109038.mp3',
    coverImage: 'https://images.unsplash.com/photo-1506126613408-eca07ce68773?q=80&w=800&auto=format&fit=crop',
    tags: ['breath', 'meditation', 'calm', 'focus'],
    releaseDate: '2024-02-01',
    isDownloadable: true,
    isExplicit: false,
    published: true,
    playCount: 1650,
    createdAt: '2024-02-01T00:00:00Z',
  },
  {
    id: 'silent-mind-02',
    slug: 'silent-mind-02',
    title: 'Witnessing Sound & Silence',
    subtitle: 'Auditory Awareness and Stillness',
    description: 'Listening to external sounds as vibration and resting in the profound stillness between sounds.',
    artistId: 'ananda-soundscapes',
    artistName: 'Ananda Soundscapes',
    seriesId: 'silent-mind-meditations',
    seriesName: 'Silent Mind: Daily Awakening',
    category: 'Meditation',
    language: 'English',
    duration: 1800, // 30 min
    trackNumber: 2,
    audioUrl: 'https://cdn.pixabay.com/download/audio/2022/01/18/audio_d0a13f69d2.mp3?filename=ambient-piano-amp-strings-10711.mp3',
    coverImage: 'https://images.unsplash.com/photo-1506126613408-eca07ce68773?q=80&w=800&auto=format&fit=crop',
    tags: ['sound', 'stillness', 'awareness'],
    releaseDate: '2024-02-02',
    isDownloadable: true,
    isExplicit: false,
    published: true,
    playCount: 1200,
    createdAt: '2024-02-01T00:00:00Z',
  },
  {
    id: 'silent-mind-03',
    slug: 'silent-mind-03',
    title: 'Resting in Pure Being',
    subtitle: 'Dissolving the Effort to Meditate',
    description: 'Moving beyond effort and technique into natural presence and calm abiding.',
    artistId: 'ananda-soundscapes',
    artistName: 'Ananda Soundscapes',
    seriesId: 'silent-mind-meditations',
    seriesName: 'Silent Mind: Daily Awakening',
    category: 'Meditation',
    language: 'English',
    duration: 1800, // 30 min
    trackNumber: 3,
    audioUrl: 'https://cdn.pixabay.com/download/audio/2022/11/06/audio_946a815a51.mp3?filename=calm-ambient-126245.mp3',
    coverImage: 'https://images.unsplash.com/photo-1506126613408-eca07ce68773?q=80&w=800&auto=format&fit=crop',
    tags: ['presence', 'being', 'silence'],
    releaseDate: '2024-02-03',
    isDownloadable: true,
    isExplicit: false,
    published: true,
    playCount: 940,
    createdAt: '2024-02-01T00:00:00Z',
  },

  // Morning Ragas Trilogy
  {
    id: 'morning-raga-01',
    slug: 'morning-raga-01',
    title: 'Raga Bhairav (Alaap & Jod)',
    subtitle: 'The Dignified Majesty of Dawn',
    description: 'A contemplative exploration of Raga Bhairav played on the Indian bamboo flute, welcoming the early light of dawn.',
    artistId: 'hariprasad-chaurasia',
    artistName: 'Pt. Hariprasad Chaurasia',
    seriesId: 'morning-ragas-trilogy',
    seriesName: 'Morning Ragas of Sunrise',
    category: 'Music',
    language: 'Instrumental',
    duration: 2400, // 40 min
    trackNumber: 1,
    audioUrl: 'https://cdn.pixabay.com/download/audio/2022/05/27/audio_1808fbf07a.mp3?filename=relaxing-mountains-nature-walk-112191.mp3',
    coverImage: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?q=80&w=800&auto=format&fit=crop',
    tags: ['classical', 'raga', 'bhairav', 'flute', 'morning'],
    releaseDate: '2024-02-10',
    isDownloadable: true,
    isExplicit: false,
    published: true,
    playCount: 3100,
    createdAt: '2024-02-10T00:00:00Z',
  },
  {
    id: 'morning-raga-02',
    slug: 'morning-raga-02',
    title: 'Raga Ahir Bhairav (Vilambit Roopak)',
    subtitle: 'The Serenity of Awakening',
    description: 'Slow rhythmic elaboration blending tenderness and devotional feeling with masterly flute tonality.',
    artistId: 'hariprasad-chaurasia',
    artistName: 'Pt. Hariprasad Chaurasia',
    seriesId: 'morning-ragas-trilogy',
    seriesName: 'Morning Ragas of Sunrise',
    category: 'Music',
    language: 'Instrumental',
    duration: 2400, // 40 min
    trackNumber: 2,
    audioUrl: 'https://cdn.pixabay.com/download/audio/2022/03/15/audio_c8c8a73467.mp3?filename=meditation-109038.mp3',
    coverImage: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?q=80&w=800&auto=format&fit=crop',
    tags: ['classical', 'ahir-bhairav', 'instrumental'],
    releaseDate: '2024-02-10',
    isDownloadable: true,
    isExplicit: false,
    published: true,
    playCount: 2200,
    createdAt: '2024-02-10T00:00:00Z',
  },
  {
    id: 'morning-raga-03',
    slug: 'morning-raga-03',
    title: 'Raga Todi (Gat in Teental)',
    subtitle: 'Deep Solitude and Reverence',
    description: 'Dynamic composition featuring delicate microtones and lively rhythmic tabla accompaniment.',
    artistId: 'hariprasad-chaurasia',
    artistName: 'Pt. Hariprasad Chaurasia',
    seriesId: 'morning-ragas-trilogy',
    seriesName: 'Morning Ragas of Sunrise',
    category: 'Music',
    language: 'Instrumental',
    duration: 2400, // 40 min
    trackNumber: 3,
    audioUrl: 'https://cdn.pixabay.com/download/audio/2022/01/18/audio_d0a13f69d2.mp3?filename=ambient-piano-amp-strings-10711.mp3',
    coverImage: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?q=80&w=800&auto=format&fit=crop',
    tags: ['todi', 'classical', 'teental', 'flute'],
    releaseDate: '2024-02-10',
    isDownloadable: true,
    isExplicit: false,
    published: true,
    playCount: 1450,
    createdAt: '2024-02-10T00:00:00Z',
  },

  // Krishnamurti Thought & Fear
  {
    id: 'krishnamurti-thought-01',
    slug: 'krishnamurti-thought-01',
    title: 'The Observer is The Observed',
    subtitle: 'Discourse on Psychological Division',
    description: 'An exploration into whether there is a thinker separate from thought, or whether the division creates endless conflict.',
    artistId: 'j-krishnamurti',
    artistName: 'J. Krishnamurti',
    seriesId: 'the-nature-of-thought',
    seriesName: 'The Nature of Thought and Fear',
    category: 'Philosophy',
    language: 'English',
    duration: 3300, // 55 min
    trackNumber: 1,
    audioUrl: 'https://cdn.pixabay.com/download/audio/2022/11/06/audio_946a815a51.mp3?filename=calm-ambient-126245.mp3',
    coverImage: 'https://images.unsplash.com/photo-1457369804613-52c61a468e7d?q=80&w=800&auto=format&fit=crop',
    tags: ['krishnamurti', 'philosophy', 'mind', 'observer'],
    releaseDate: '1982-05-12',
    isDownloadable: false,
    isExplicit: false,
    published: true,
    playCount: 760,
    createdAt: '2024-03-01T00:00:00Z',
  },
  {
    id: 'krishnamurti-thought-02',
    slug: 'krishnamurti-thought-02',
    title: 'Ending Fear at Its Root',
    subtitle: 'Understanding Time and Psychological Security',
    description: 'How fear is born out of thought projecting time, and the possibility of total freedom in immediate direct attention.',
    artistId: 'j-krishnamurti',
    artistName: 'J. Krishnamurti',
    seriesId: 'the-nature-of-thought',
    seriesName: 'The Nature of Thought and Fear',
    category: 'Philosophy',
    language: 'English',
    duration: 3300, // 55 min
    trackNumber: 2,
    audioUrl: 'https://cdn.pixabay.com/download/audio/2022/05/27/audio_1808fbf07a.mp3?filename=relaxing-mountains-nature-walk-112191.mp3',
    coverImage: 'https://images.unsplash.com/photo-1457369804613-52c61a468e7d?q=80&w=800&auto=format&fit=crop',
    tags: ['krishnamurti', 'fear', 'time', 'freedom'],
    releaseDate: '1982-05-14',
    isDownloadable: false,
    isExplicit: false,
    published: true,
    playCount: 690,
    createdAt: '2024-03-01T00:00:00Z',
  },
];

